version: '3.8'

services:
  api-gateway:
    build: avox_services/api_gateway
    env_file:
      - avox_services/api_gateway/.env
    depends_on:
      - auth
      - task-manager
    ports:
      - "8000:8000"
    networks:
      - avox_net
    labels:
      com.docker.compose.project: avox

  auth:
    build: avox_services/auth
    env_file:
      - avox_services/auth/.env
    depends_on:
      - redis
    ports:
      - "8001:8001"
    networks:
      - avox_net
    labels:
      com.docker.compose.project: avox

  task-manager:
    build: avox_services/task_manager
    env_file:
      - avox_services/task_manager/.env
    depends_on:
      - postgres
    ports:
      - "8002:8002"
    networks:
      - avox_net
    labels:
      com.docker.compose.project: avox

  llm-service:
    build: avox_services/LLM_service
    env_file:
      - avox_services/LLM_service/.env
    depends_on:
      - postgres
    ports:
      - "8003:8003"
    networks:
      - avox_net
    labels:
      com.docker.compose.project: avox

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - avox_net
    labels:
      com.docker.compose.project: avox

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avox
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - avox_net
    labels:
      com.docker.compose.project: avox

volumes:
  pg_data:

networks:
  avox_net:
    driver: bridge
