"""initial

Revision ID: 96dca092eda9
Revises: 
Create Date: 2025-06-29 18:26:48.019150

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96dca092eda9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='llm'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vk_id', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('EDITOR', 'READER', 'CLIENT', name='roletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['llm.companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_id'),
    schema='llm'
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('URI', 'CONFLUENCE', 'FILE', 'TEXT_INPUT', 'WEB_SCRAPING', name='sourcetype'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('access_level', sa.Enum('PRIVATE', 'PUBLIC', 'SHARED', 'TEAM', 'RESTRICTED', name='accesslevel'), nullable=False),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['llm.companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['llm.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='llm'
    )
    op.create_table('access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['llm.documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['llm.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='llm'
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_idx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['llm.documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='llm'
    )
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.Vector(dim=512), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SCHEDULED', name='embeddingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['llm.document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='llm'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_embeddings', schema='llm')
    op.drop_table('document_chunks', schema='llm')
    op.drop_table('access_grants', schema='llm')
    op.drop_table('documents', schema='llm')
    op.drop_table('users', schema='llm')
    op.drop_table('companies', schema='llm')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
