"""refactor_embeddings_tables

Revision ID: 6e93533354e2
Revises: 8d4ca6140cd3
Create Date: 2025-07-13 23:25:10.672636

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e93533354e2'
down_revision: Union[str, Sequence[str], None] = '8d4ca6140cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_embeddings_384', sa.Column('embedding_scope', sa.String(length=64), nullable=False, comment='Область эмбеддинга: chunk, subchunk и др.'), schema='kno')
    op.add_column('chunk_embeddings_384', sa.Column('subchunk_idx', sa.Integer(), nullable=False, comment='Порядковый номер подчанка внутри фрагмента'), schema='kno')
    op.add_column('chunk_embeddings_384', sa.Column('overlap', sa.Integer(), nullable=False, comment='Количество перекрывающихся единиц (слов, токенов и т.п.) между подчанками'), schema='kno')
    op.add_column('chunk_embeddings_384', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='embeddingstatus'), nullable=False, comment='Статус эмбеддинга: pending, processing, completed, completed'), schema='kno')
    op.add_column('chunk_embeddings_384', sa.Column('attempts', sa.Integer(), nullable=False, comment='Количество попыток обработки'), schema='kno')
    op.add_column('chunk_embeddings_384', sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке при обработке эмбеддинга'), schema='kno')
    op.add_column('document_chunks', sa.Column('chunk_scope', sa.String(length=64), nullable=True, comment='Единица разбиения чанка: symbols, words, sentence'), schema='kno')
    op.add_column('document_chunks', sa.Column('overlap', sa.Integer(), nullable=False, comment='Количество перекрывающихся единиц (слов, предложений и т.п.) между чанками'), schema='kno')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'overlap', schema='kno')
    op.drop_column('document_chunks', 'chunk_scope', schema='kno')
    op.drop_column('chunk_embeddings_384', 'error_message', schema='kno')
    op.drop_column('chunk_embeddings_384', 'attempts', schema='kno')
    op.drop_column('chunk_embeddings_384', 'status', schema='kno')
    op.drop_column('chunk_embeddings_384', 'overlap', schema='kno')
    op.drop_column('chunk_embeddings_384', 'subchunk_idx', schema='kno')
    op.drop_column('chunk_embeddings_384', 'embedding_scope', schema='kno')
    # ### end Alembic commands ###
